### ISSUE TITLE
Please add the equivalent of the `IncludeChain` HTTP header 

### ISSUE THREAD

**Issue by djk** [keyfactor-pub/terraform-provider-keyfactor#45]
At the moment when you recover a certificate using the data source `keyfactor_certificate`, you can access the `certificate_chain` or `certificate_pem`. 

Could there be an option to recover these combined like the API call you can do that uses the `IncludeChain` header to get both in one call?

Thanks a lot.

**Comment by spbsoluble** [comment]
Sounds reasonable to me we'll try and get this out in the next release.

**Comment by spbsoluble** [comment]
@djk this has been added to v2.0.0, by default the `certificate_chain` will now contain a full chain and a new field `ca_certificate` has been added which will contain the chain without the leaf.
