### ISSUE TITLE
Configurable timeout

### ISSUE THREAD

**Issue by djk** [keyfactor-pub/terraform-provider-keyfactor#47]
Very regularly the provider fails with `Unable to create client` due to a `Client.Timeout` being exceeded.

This seems to happen after 10s. Could the timeout be configurable? I am using the official Keyfactor API, not anything self-hosted so there's nothing I can do about improving performance to this endpoint myself. 

Thanks

**Comment by spbsoluble** [comment]
I typically get this error the first time I run a terraform command after ~24 hrs, then on the subsequent runs everything seems fine, I'll look into adding additional timeout time resolves this.

**Comment by spbsoluble** [comment]
@djk this hasn't been added as a configurable but v2.0.0 will retry a few times if it hits that error. Let me know if you are still hitting this issue, and it'll get added as configurable in the next release.

**Comment by djk** [comment]
@spbsoluble Thanks! Will give it a shot when I can!
