### ISSUE TITLE
Certificate removal returns success before certificate actually removed from the store

### ISSUE THREAD

**Issue by rmcolbert** [keyfactor-pub/terraform-provider-keyfactor#53]
When removing a certificate from a cert store, the provider confirms the removal before the management job completes. This could this will cause issues if the management job fails.

This does not appear to be the case when deploying a cert to a store. Terraform appears to wait (or throw an error) if the certificate isn't deployed to the store in a set timeout.

Can we please have the same job validation on removal?

**Comment by spbsoluble** [comment]
@rmcolbert this has been addressed and released with v2.0.0
