### ISSUE TITLE
Certificates being replaced on every execution if optional list values are not provided.

### ISSUE THREAD

**Issue by rmcolbert** [keyfactor-pub/terraform-provider-keyfactor#66]
When creating a PFX cert, we are leaving out the dns_sans, ip_sans & uri_sans parameters. 
These fields are being stored in the state file as null but when Terraform retrieves the cert, they are being calculated as empty lists. 

```
      - dns_sans              = [] -> null # forces replacement
      - ip_sans               = [] -> null # forces replacement
      - uri_sans              = [] -> null # forces replacement
```    

The provider defaults for those parameters should be stored as [].

**Comment by rmcolbert** [comment]
Related bug: Command may return the lists in a different order than what Terraform requested causing the certificate to be reissued.

**Comment by spbsoluble** [comment]
Null replacements are addressed in v2.1.0.

As for the ordering issue @rmcolbert I was able to prevent this by ordering the list with `sort()` 
```
resource "keyfactor_certificate" "pkcs12_enrollment" {
  common_name   = "My PKCS12 Certificate"
  ip_sans                = sort(["192.168.123.2", "172.51.2.4"])
  dns_sans            = sort(["my.pkcs12.io", "My PKCS12 Certificate", "my.pkcs12.co.uk", "Certificate PKCS12 My"])
  uri_sans              = sort(["my.pkcs12.io"])
  certificate_authority = "COMMAND\\MY_CA_01"
  certificate_template  = "2yrWebServer"
}
```
does that resolve your issue as well?

**Comment by rmcolbert** [comment]
While that is a valid workaround, the provider should provide a consistent view of the object without the dev having to modify the inputs because the object returned doesn't match.

Can you sort the inputs inside the provider so that it matches the return from Command?

Also, sort didn't seem to work when my dns_san also included my certificate's common name (which is how most non-wildcard certs are generated)

**Comment by spbsoluble** [comment]
Arbitrary order should no longer trigger replacement in v2.1.3
