### ISSUE TITLE
Certificates being replaced if template short name and template display name are different

### ISSUE THREAD

**Issue by rmcolbert** [keyfactor-pub/terraform-provider-keyfactor#67]
When creating a certificate, the provider expects the template short name but when the certificate is read back, the display name is being returned. This is causing certificates to be replaced by Terraform.

`      ~ certificate_template  = "Web Server" -> "WebServer" # forces replacement`

In our current configuration, we have a cert template "Web Server" with the short name "WebServer".

This isn't an issue if the Display Name and Short Name are the same.

**Comment by spbsoluble** [comment]
This seems to be caused by the fact that when the Command API returns a certificate resource it returns the display name, rather than short name, in the `TemplateName` field. This has been addressed by doing an additional lookup after the cert is read on the `TemplateId` field.

**Comment by spbsoluble** [comment]
Resolved in v2.1.0
