### ISSUE TITLE
Upgrading from 2.0 to 2.1 breaks existing cert resources.

### ISSUE THREAD

**Issue by rmcolbert** [keyfactor-pub/terraform-provider-keyfactor#72]
After upgrading to v2.1.0 of the provider, the plan phase fails on PFX certs created using v2.0 and providing and the (then required)  key_password,

```
│ Error: Error reading Keyfactor certificate.
│
│   with keyfactor_certificate.PFXCertificate[0],
│   on main.tf line 18, in resource "keyfactor_certificate" "PFXCertificate":
│   18: resource "keyfactor_certificate" "PFXCertificate" {
│
│ Could not retrieve certificate '15965' from Keyfactor: password required to recover private key with certificate

```

I have not tested this upgrade path w/ the v1 provider to see if it would impact PFX certs created with that provider.

I tried commenting out the key_password input that was provided in the 2.0 cert request but received the same error.

Steps to reproduce:
1. Generate a PFX cert using the 2.0.0 provider
2. Upgrade to the 2.1.0 provider
3. Attempt to run `terraform plan` or `terraform apply`

**Comment by spbsoluble** [comment]
Upgrading to 2.1.2 should address this issue.
