### ISSUE TITLE
PFX Certificate gets replaced if key_password input changed or removed

### ISSUE THREAD

**Issue by rmcolbert** [keyfactor-pub/terraform-provider-keyfactor#74]
In v2.1.0, If a key_password is provided during PFX certificate creation and subsequently removed or changed, the entire certificate gets recreated.

Should key_password require recreation of the certificate or if auto_password remains the same (i.e. key_password removed/set to null), the cert object would still be valid.

If key_password is updated, could the provider simply regenerate the private key without recreating the entire certificate?

**Comment by spbsoluble** [comment]
This is not possible which is why it forces replacement. There's no API exposed to update the password needed to recover the private key, so a new enrollment must be performed.

**Comment by rmcolbert** [comment]
The data resource for a certificate does a recovery when you give it a password. Is that different from what the provider does here?

Also, when switching from an empty string to null for key_password, Terraform is rerolling the auto_password can causing the certificate to be recreated. Since we are switching between non-values, it would be nice if the provider equated null and empty string as the same value and didn't force the cert to be recreated.

**Comment by spbsoluble** [comment]
>The data resource for a certificate does a recovery when you give it a password. Is that different from what the provider does here?

The data source attempts a recovery, same as the resource read, if no password is provided or is invalid, the private key is silently not recovered. So in cases where you want to data source a cert with a stored private key not created by Terraform, and you don't know the password you won't be able to recover the private key. As a work around, you need to download the cert from the Command UI and include the private key. Command will then generate a password for that download and you can reference that password in your Terraform code to allow recovery. 

>Also, when switching from an empty string to null for key_password, Terraform is rerolling the auto_password can causing the certificate to be recreated. Since we are switching between non-values, it would be nice if the provider equated null and empty string as the same value and didn't force the cert to be recreated.

I agree, this seems like a bug to fix.

**Comment by spbsoluble** [comment]
@rmcolbert It seems my understanding of how Command handles passwords was incorrect. The password at recovery time can essentially be anything and Command does not store this. However it should be noted that at create time if the password isn't sufficiently complex, which depends on template config, then enrollment will fail with an ambiguous error stating to check the server logs. With this means that it triggering a force replace on password change no longer seems appropriate and v2.1.4 has removed that behavior.
