### ISSUE TITLE
Updated cert store properties failure

### ISSUE THREAD

**Issue by rmcolbert** [keyfactor-pub/terraform-provider-keyfactor#84]
Attempting to update the properties block on a keyfactor_certificate_store resulted in an update failure.

```
keyfactor_certificate_store.kv_existing_store: Modifying... [id=edb8127d-d493-44eb-8d16-afc08845e598]
╷
│ Error: Error updating certificate store
│
│   with keyfactor_certificate_store.kv_existing_store,
│   on main.tf line 101, in resource "keyfactor_certificate_store" "kv_existing_store":
│  101: resource "keyfactor_certificate_store" "kv_existing_store" {
│
│ Error updating certificate store: %sThe CertificateStore 'Properties' property is invalid. 'null'
╵
```

The only thing being changed in the code was the ServerPassword property.

**Comment by spbsoluble** [comment]
@rmcolbert I'm not sure I completely understood how to reproduce that issue, but I did fix a few different scenarios with the properties string in `v2.1.5` that may also address this issue you're having. Also, just FYI the `ServerPassword` parameter was given its' own explicit attribute `server_password` as of `v2.0.0` which allows it to be marked as `sensitive`.
