### ISSUE TITLE
Can't enroll PFX

### ISSUE THREAD

**Issue by djk** [keyfactor-pub/terraform-provider-keyfactor#95]
Using version 2.1.5 of the provider, I am trying to create a PFX using the `keyfactor_certificate` resource. The error is `Enrolling for a pfx will result in a suspended workflow which is not supported for this version of the API. Please use version 2 instead.` 

I note that in the `keyfactor-go-client` that the header that sets the API version, appears to be hardcoded to `1` instead of `2`. 

Is this a big change to make? Does it just need the header to be parameterised? 

Thanks!

**Comment by spbsoluble** [comment]
@djk upgrading to v2.1.6 should solve this for you.
